export const MAX_USER_NAME_LENGTH = 20;
export const MAX_PROJECT_NAME_LENGTH = 20;
export const MAX_PROJECT_DESCRIPTION_LENGTH = 100;
export const MAX_COMMENT_SEARCH_TERM_LENGTH = 255;
export const MAX_PROFILE_IMAGE_SIZE = 1024 * 1024 * 5;
