export const NUM_OF_COMMENTS_PER_PAGE = 5;
export const INITIAL_PAGE_PARAM = 1;
export const MAX_COMMENT_INPUT_LENGTH = 1000;
export const GUEST_NICKNAME_MIN_LENGTH = 1;
export const GUEST_NICKNAME_MAX_LENGTH = 20;
export const GUEST_PASSWORD_MIN_LENGTH = 1;
export const GUEST_PASSWORD_MAX_LENGTH = 20;
