# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Darass PR Checker - dev [FE]

on:
  pull_request:
    types: [ opened, edited ]
    branches: [ main ]

jobs:
  build:

    runs-on: [self-hosted, front]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '14'
        
    - run: npm install
    
    - name: Setup yarn
      run: npm install -g yarn
      
    - name: Install Dependencies - comment
      run: yarn install
      working-directory: ./frontend/reply-module
      
    - name: Test - comment
      run: yarn test
      working-directory: ./frontend/reply-module
    
    - name: Build - comment
      run: yarn build
      working-directory: ./frontend/reply-module
      env:
        KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
        KAKAO_JAVASCRIPT_API_KEY: ${{ secrets.KAKAO_JAVASCRIPT_API_KEY }}
        SENTRY_REPLY_MODULE_DSN: ${{ secrets.SENTRY_REPLY_MODULE_DSN }}
        NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
      
    - name: Install Dependencies - project
      run: yarn install
      working-directory: ./frontend/manage
      
    - name: Test - project
      run: yarn test
      working-directory: ./frontend/manage
    
    - name: Build - project
      run: yarn build
      working-directory: ./frontend/manage
      env:
        KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
        KAKAO_JAVASCRIPT_API_KEY: ${{ secrets.KAKAO_JAVASCRIPT_API_KEY }}
        SENTRY_MANAGE_PAGE_DSN: ${{ secrets.SENTRY_MANAGE_PAGE_DSN }}
        NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
    
    - name: Install Dependencies - deploy script
      run: yarn install
      working-directory: ./frontend/deploy-script
    
    - name: Build - deploy script
      run: yarn build
      working-directory: ./frontend/deploy-script
  
    - name: build result to slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo, message, commit, author, action, eventName, ref, workflow, job, took
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FRONT }}
      if: always()
